### ISSUE TITLE
Command [/usr/local/bin/dub path /var/lib/kafka/data writable] FAILED !

### ISSUE THREAD

**Issue by SarthakGhosh16** [confluentinc/kafka-images#131]
I'm using kafka image v6.1.4-2-ubi8 pulled from https://hub.docker.com/layers/confluentinc/cp-kafka/6.1.4-2-ubi8/images/sha256-f3edca939e7484f5930eb91a8a42c5a30bf0b8e2556400c6677509b20cb26510?context=explore

Building my own Docker using above and using it in a kubernetes pod

While trying to run the image, I am getting the mentioned error
```
===> User
uid=1000670000(1000670000) gid=0(root) groups=0(root),1000670000
===> Configuring ...
SSL is enabled.
===> Running preflight checks ...
===> Check if /var/lib/kafka/data is writable ...
Command [/usr/local/bin/dub path /var/lib/kafka/data writable] FAILED !
```

I tried a lot of changes but nothing seems to work
```
USER root

RUN yum -y update --disableplugin=subscription-manager && \ 
	yum -y upgrade --disableplugin=subscription-manager && \
	groupadd -g 1001 fcigroup && \
  useradd -u 1001 -g 1001 -m fciuser && \
  chown -R fciuser: /var/lib/kafka && \
  chown -R fciuser: /home && \
  chown -R fciuser: /etc && \
  chown -R fciuser: /var/lib/kafka/data && \
  chmod -R 777 /var/log/kafka && \
  chmod -R 777 /home && \
  chmod -R 777 /etc/kafka && \
  chmod -R 777 /var/lib/kafka && \
  chmod -R 777 /var/lib/kafka/data

USER 1001
```

I even removed `USER 1001` but even that didn't seem to solve my issue

```
USER root

RUN yum -y update --disableplugin=subscription-manager && \ 
	yum -y upgrade --disableplugin=subscription-manager && \
  chmod -R a+rwx /var/log/kafka && \
  chmod -R a+rx /home && \
  chmod -R a+rwx /var/lib/kafka && \
  chmod -R a+rwx /var/lib/kafka/data && \
  chmod -R a+rwx /etc/kafka
```

I had to add `/etc/kafka` because earlier even that was throwing similar error

Any help is appreciated

**Comment by jon-king-mindbodyonline** [comment]
Same as closed #127 which says to open new issues if still encountering.
I'm also getting this today, with `docker.io/confluentinc/cp-kafka-connect-base:5.5.7@sha256:41129d946c983f874fbf79586ea0aa6dd9f5dc6cf11509a5b8ec6efe8b558245` which is the latest for 5.5.7

**Comment by andrewegel** [comment]
> uid=1000670000(1000670000) gid=0(root) groups=0(root),1000670000

This looks like you're using things in openshift akin to: https://cloud.redhat.com/blog/a-guide-to-openshift-and-uids and this discussion here: https://github.com/confluentinc/schema-registry-images/pull/48#issuecomment-993532523

If so, I'll be working on these fixes in the coming weeks.

**Comment by SarthakGhosh16** [comment]
Hi @andrewegel 
yes, we are deploying on an openshift cluster and the [DISCUSSION](https://github.com/confluentinc/schema-registry-images/pull/48#issuecomment-993532523) you shared captures the issue perfectly.

Is there an issue I can track or will you be using this one?

**Comment by andrewegel** [comment]
> yes, we are deploying on an openshift cluster... Is there an issue I can track or will you be using this one?

Great, thanks for confirming - We can track things here. I have some in-flight PRs I'll list here that I believe will resolve things:

* https://github.com/confluentinc/kafka-images/pull/133
* https://github.com/confluentinc/schema-registry-images/pull/52
* https://github.com/confluentinc/kafka-rest-images/pull/33
* https://github.com/confluentinc/kafka-mqtt-images/pull/26
* https://github.com/confluentinc/control-center-images/pull/48

Internally we're testing these changes to validate things are resolved before we merge & do mass rebuilds & re-releases of images. ETA is within the next couple of weeks. I will update things here as we make progress.

**Comment by andrewegel** [comment]
Hello folks-

After verifying these fixes worked in an OpenShift cluster with a random-uid-but-root-group runAs user, we have verified that this issue is no longer present. For the time being, I have pushed new a new `6.2.2-3-ub8` tag, and updated the `6.2.2` tag to these new images.

The following releases will also see this update something this week (I will update this issue as we release them):

* 5.4.6
* 5.5.7
* 6.0.5
* 6.1.4
* 7.0.1

**Comment by andrewegel** [comment]
I believe this issue to be resolved - Please ensure you pull the latest sem-ver tag off of DockerHub, or use one of the `-3-ubi8` suffixed tags.

Please report any further issues here - I'll close out the issue in apox one week if I don't see anything further reported here.

**Comment by SarthakGhosh16** [comment]
Thanks for fixing the issue @andrewegel 
I tested `6.1.4-3-ubi8` on my openshift cluster and it is working fine now. We are good to close this issue.

**Comment by shitaljoshi** [comment]
I am still seeing this error. 
===> User
uid=1001 gid=1001 groups=1001
===> Configuring ...
Command [/usr/local/bin/dub path /etc/kafka-connect/ writable] FAILED !
I am using confluentinc/cp-kafka-connect-base:7.0.1-3-ubi8

**Comment by JinnaBalu** [comment]
Update your docker-compose with user:root, this will resolve the issues.

**Comment by buffaloDeveloper** [comment]
This issue is still not fixed.

**Comment by sugan2111** [comment]
> I am still seeing this error. ===> User uid=1001 gid=1001 groups=1001 ===> Configuring ... Command [/usr/local/bin/dub path /etc/kafka-connect/ writable] FAILED ! I am using confluentinc/cp-kafka-connect-base:7.0.1-3-ubi8

Hi @shitaljoshi , I am also facing this similar issue, did you get it to work?

**Comment by DilLip-Chowdary-Codes** [comment]
@sugan2111 @shitaljoshi @buffaloDeveloper  Did you find any fix for this?

**Comment by lucasramosdev** [comment]
> Update your docker-compose with user:root, this will resolve the issues.
> 
> ```yaml
> kafka-connect:
>     image: confluentinc/cp-kafka-connect-base:6.2.0
>     container_name: kafka-connect
>     user: root
>    ......
> ```

Worked for me! :D

**Comment by jahands** [comment]
Thank you @lucasramosdev - needed this today when updating to `24.9.0`

**Comment by CyrilleLyam** [comment]
update user:root inside docker-compose, it work fine for me
